### ISSUE TITLE
several installer issues

### ISSUE THREAD

**Issue by luclu** [ethereum/mist#1180]
```
Version: `0.8.3`
OS & Version: windows
```

The latest push of the `0.8.3` during the devcon2 to mitigate the recent geth stalling-bug (see https://github.com/ethereum/mist/issues/1169) did include a half-baked version of the new installer.

Known issues are:
- [x] missing desktop-shortcut and startmenu entries (windows) https://github.com/ethereum/mist/pull/1211
- [x] installation of Ethereum Wallet will wipe out Mist and vice versa (windows, linux) https://github.com/ethereum/mist/issues/1178
- [ ] if using Ethereum Wallet, previous configurations are not carried over https://github.com/ethereum/mist/issues/1174
- [ ] > make new installer follow license requirements #1171 

Improvements:
- [ ] create `rpm` as well as `deb` packages https://github.com/ethereum/mist/issues/1190
- [ ] improve package metadata

**Comment by luclu** [comment]
Superseded by https://github.com/ethereum/mist/pull/1499
