### ISSUE TITLE
Do not connect to network by default

### ISSUE THREAD

**Issue by fulldecent** [ethereum/mist#3476]
**Currently, every time you open Ethereum Wallet it attempts to connect to and sync the network. This is unnecessary and SHOULD NOT be enabled by default.**

# Why?

1. Currently, it takes 7+ days to open the application for the first time, this is a well-known problem. Any update to Mist's current design can only reduce, but not eliminate, this problem.

2. Core functionality such as signing and verifying messages, and creating a wallet, DO NOT REQUIRE INTERNET ACCESS. I assume Mist has all these features built in (but can't be sure since README.md has no screenshots and because a didn't wait the seven days).

3. Secondary functionality, such as transmitting a signed message onto the network DOES NOT REQUIRE A FULL BLOCKCHAIN HISTORY.

4. myetherwallet.com should have no reason to exist when you can download a RELIABLE and FAST native client.

There is a clear distinction between operations which can be done RIGHT AWAY with a FUN and EASY TO USE app that STARTS UP RIGHT AWAY versus what requires DOWNLOADING 50GB and WAITING SEVEN DAYS TO OPEN THE APP.

---

# Work plan

- [ ] Identify which dapps or builtin functions can be run in OFFLINE mode
- [ ] Identify which dapps or builtin functions can be run in THIN CLIENT (no blockchain history required) mode
- [ ] Start the app in THIN CLIENT mode or OFFLINE mode
- [ ] Check whether FULL CLIENT mode is required before starting a dapp or builtin function
- [ ] If FULL CLIENT mode is required for a dapp or builtin function then properly explain to the user what they should expect

**Comment by fulldecent** [comment]
^^ This issue will provide relief to #3349 #3445 #3113 #3101 #3458 #3355 #3109 and many other duplicate issues where people are stuck on the loading screen and have not even experienced the main application.

**Comment by Sirsmokesalotta** [comment]
Thank you.

**Comment by gciriani** [comment]
I would have expected more thumbs up and more subscribers. Why is it that this problems affects so many and so onerously, but there is little interest in following or building up momentum to solve it?

**Comment by fulldecent** [comment]
As a first step, has anyone else actually gotten Mist to open? Would you please share a good amount of screenshots with the major features. 

If you can do this, it will help us on work plan items \#1 and \#2.

**Comment by evertonfraga** [comment]
We're currently implementing remote node integration with Infura while waiting for Geth's Light client improvements.

Although we don't have an estimative to the offline use of the wallet (sign messages in an air-gapped computer), we plan to remove the requirement of the Splash Screen and waiting times.

**Comment by christopherferris** [comment]
How is it unnecessary? To check my recent balances and transactions don't I need to be synced?

**Comment by gciriani** [comment]
Christopher, to check balances and transactions you only need
https://etherscan.io/ and your account number.



On Thu, Mar 22, 2018 at 7:44 PM, christopherferris <notifications@github.com

**Comment by christopherferris** [comment]
Oh okay and for sending I needn't be synced either?

**Comment by ForauDNB** [comment]
> We're currently implementing remote node integration with Infura while waiting for Geth's Light client improvements.
> 
> Although we don't have an estimative to the offline use of the wallet (sign messages in an air-gapped computer), we plan to remove the requirement of the Splash Screen and waiting times.

Is this implemented? If so could you forward me to a resource explaining how? Having trouble finding any documentation.

**Comment by evertonfraga** [comment]
@ForauDNB yep, it is implemented. You can find more information on [version 0.11.0 release notes](url
https://github.com/ethereum/mist/releases/tag/v0.11.0), [this issue](https://github.com/ethereum/mist/issues/3673).
