### ISSUE TITLE
Improve Packaging and Distribution

### ISSUE THREAD

**Issue by luclu** [ethereum/mist#561]
Pooling related issues:
- [x] Update alert https://github.com/ethereum/mist/issues/152
- [x] Refactor gulp https://github.com/ethereum/mist/issues/832
  - [x] Externalize geth nodes from repo #670 
  - [x] Evaluate `--platforms` flag while downloading nodes
  - [x] Externalize nodes from repo, download on-demand https://github.com/ethereum/mist/pull/1228
- [x] Leverage Continues Integration via travis-ci (groundwork laid in https://github.com/ethereum/mist/pull/782)
  - [x] Switch travis-ci build environment to macosx #1182 
  - [x] Make builds available for download https://github.com/ethereum/mist/issues/1143
  - [x] Automated UI Testing (groundwork laid in https://github.com/ethereum/mist/pull/788)
- [x] Switch to [electron-builder](https://www.npmjs.com/package/electron-builder) https://github.com/ethereum/mist/pull/972
  - [ ] in-App updater
  - [ ] Windows Installer & App signing #850 
  - [ ] App signing on OSX #47
  - [ ] Apple App Store integration
- [x] Homebrew Cask integration
- [ ] Chocolatey integration https://github.com/ethereum/mist/issues/882
- [ ] Update oracle https://github.com/ethereum/mist/issues/152#issuecomment-216880480
- [x] PGP Validation on Mist Releases #546 
- [ ] Deterministic builds #560

**Comment by root-io** [comment]
Ethereum Wallet was added into Homebrew Cask. See https://github.com/caskroom/homebrew-cask/pull/24640

**Comment by luclu** [comment]
This is awesome @root-io - thank you very much!

**Comment by alexvandesande** [comment]
Thanks for having this list Luca, it was very useful in 2016 but I feel we can close it now. Hope you are doing well in your current adventures!
